workflows:
  android-release:
    name: Android Release (AAB)
    max_build_duration: 90
    environment:
      flutter: 3.7.12
      java: 11
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          echo "flutter.versionName=1.0.2" >> android/local.properties
          echo "flutter.versionCode=37" >> android/local.properties
      - name: Get packages
        script: flutter pub get
      - name: Generate app icons
        script: flutter pub run flutter_launcher_icons:main
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release \
            --build-name=1.0.2 \
            --build-number=37
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
